[phases.setup]
nixPkgs = ["php", "phpExtensions.mysqli", "phpExtensions.mbstring", "phpExtensions.curl", "phpExtensions.mongodb"]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
